services:
  ice-server-v2:
    hostname: ice-server-v2
    privileged: true
    cap_add:
    - SYS_ADMIN
    image: ice-server-v2
    ports:
      - "5000:3000"
    container_name: ice-server-container-v2 
    networks:
      cabin:
        ipv4_address: 192.167.50.10
      auditorium:
        ipv4_address: 192.50.50.10

  ice-panel-v2:
    hostname: ice-panel-v2
    image: gitlab.cgrcinemas.fr:5050/martin.lagrange/icedeviceemulator:latest
    container_name: ice-panel-container-v2 
    networks:
      auditorium:
        ipv4_address: 192.50.50.3

  ice-server-central-v2:
    hostname: ice-server-central-v2
    image: ice-server-central-v2
    ports:
      - "8000:3000"
      - "9229:9229"
    container_name: ice-server-container-central-v2 
    networks:
      cabin:
        ipv4_address: 192.167.50.1

networks:
  cabin:
    name: "cabin"
    driver: bridge
    ipam:
      config:
        - subnet: "192.167.0.0/16"     
  auditorium:
      name: "auditorium"      
      driver: bridge
      ipam:
        config:
          - subnet: "192.50.0.0/16"