CREATE DATABASE  IF NOT EXISTS `ice` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE `ice`;
SET NAMES 'utf8mb4';

CREATE USER IF NOT EXISTS "cinelight"@"localhost" IDENTIFIED BY "R@qazwsx2";
GRANT ALL PRIVILEGES ON *.* TO `cinelight`@`localhost` WITH GRANT OPTION;